max-afk-seconds: 300
max-clicks-per-second: 10
enable-water-loop-detection: true
enable-auto-clicker-detection: true
kick-message-afk: "&cYou have been kicked for being AFK."
kick-message-water-loop: "&cYou have been kicked for using a water loop."
kick-message-auto-clicker: "&cYou have been kicked for using an auto-clicker."
auto-clicker-time-threshold: 300 # 5 minutes
auto-clicker-warning-interval: 30 # 30 seconds
water-loop-movement-threshold: 20
water-loop-time-threshold: 300 # 5 minutes